const { transform } = require('../../api/fn/transformFunctions');

const dataItem = 
  [{
    id: 373482697,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNzM0ODI2OTc=',
    name: 'm2Digital',
    full_name: 'joicerodrigues/m2Digital',
    private: false,
    html_url: 'https://github.com/joicerodrigues/m2Digital',
    description: 'REPL for Prisma databases.',
    fork: false,
    url: 'https://api.github.com/repos/joicerodrigues/m2Digital',
    forks_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/forks',
    keys_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/teams',
    hooks_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/hooks',
    issue_events_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/issues/events{/number}',
    events_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/events',
    assignees_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/assignees{/user}',
    branches_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/branches{/branch}',
    tags_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/tags',
    blobs_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/languages',
    stargazers_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/stargazers',
    contributors_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/contributors',
    subscribers_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/subscribers',
    subscription_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/subscription',
    commits_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/contents/{+path}',
    compare_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/merges',
    archive_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/downloads',
    issues_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/issues{/number}',
    pulls_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/labels{/name}',
    releases_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/releases{/id}',
    deployments_url: 'https://api.github.com/repos/joicerodrigues/m2Digital/deployments',
    created_at: '2022-07-02T06:42:39Z',
    updated_at: '2022-07-17T21:06:57Z',
    pushed_at: '2022-07-02T19:42:39Z',
    git_url: 'git://github.com/joicerodrigues/m2Digital.git',
    ssh_url: 'git@github.com:joicerodrigues/m2Digital.git',
    clone_url: 'https://github.com/joicerodrigues/m2Digital.git',
    svn_url: 'https://github.com/joicerodrigues/m2Digital',
    homepage: null,
    size: 103,
    stargazers_count: 162,
    watchers_count: 162,
    language: 'PHP',
    has_issues: true,
    has_projects: false,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 1,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 12,
    license: [Object],
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 1,
    open_issues: 12,
    watchers: 162,
    default_branch: 'main',
    score: 1,
  }];

const transformed = [{
  createdAt: '2022-07-02 08:42',
  language: 'PHP',
  name: 'm2Digital',
  url: 'https://github.com/joicerodrigues/m2Digital',
}];

test('transforms properties', () => expect(transform(dataItem)).toStrictEqual(transformed));
